# Hard-coding a list of features as a reference so that other modules can be sure of the feature count / order
features = [
    "AbsoluteBasophilCount",
    "AbsoluteEosinophilCount",
    "AbsoluteLymphocyteCount",
    "AbsoluteMonocyteCount",
    "AbsoluteNeutrophilCount",
    "AtypicalLymphocytes",
    "Bands",
    "Basophils",
    "Blasts",
    "EosinophilCount",
    "Eosinophils",
    "GranulocyteCount",
    "HypersegmentedNeutrophils",
    "ImmatureGranulocytes",
    "Lymphocytes",
    "LymphocytesPercent",
    "Metamyelocytes",
    "MonocyteCount",
    "Monocytes",
    "Myelocytes",
    "Neutrophils",
    "NucleatedRedCells",
    "OtherCells",
    "PlateletCount",
    "Promyelocytes",
    "RedBloodCells",
    "ReticulocyteCountAbsolute",
    "ReticulocyteCountAutomated",
    "WBCCount",
    "WhiteBloodCells",
    "aado2",
    "aado2_calc",
    "albumin",
    "alp",
    "alt",
    "amylase",
    "aniongap",
    "ast",
    "baseexcess",
    "bicarbonate",
    "bilirubin_direct",
    "bilirubin_indirect",
    "bilirubin_total",
    "bun",
    "calcium",
    "carboxyhemoglobin",
    "chloride",
    "ck_cpk",
    "ck_mb",
    "creatinine",
    "crp",
    "d_dimer",
    "diastolic_bp",
    "fibrinogen",
    "fio2",
    "ggt",
    "globulin",
    "glucose",
    "heart_rate",
    "hematocrit",
    "hemoglobin",
    "inr",
    "invasive_line",
    "lactate",
    "ld_ldh",
    "methemoglobin",
    "pao2fio2ratio",
    "pco2",
    "ph",
    "po2",
    "potassium",
    "pt",
    "ptt",
    "resp_rate",
    "so2",
    "sodium",
    "spo2",
    "systolic_bp",
    "temperature",
    "thrombin",
    "total_protein",
    "totalco2",
    "ventilation",
]

feat_category_map = {
    "AbsoluteBasophilCount": "CBC",
    "AbsoluteEosinophilCount": "CBC",
    "AbsoluteLymphocyteCount": "CBC",
    "AbsoluteMonocyteCount": "CBC",
    "AbsoluteNeutrophilCount": "CBC",
    "AtypicalLymphocytes": "CBC",
    "Bands": "CBC",
    "Basophils": "CBC",
    "Blasts": "CBC",
    "EosinophilCount": "CBC",
    "Eosinophils": "CBC",
    "GranulocyteCount": "CBC",
    "HypersegmentedNeutrophils": "CBC",
    "ImmatureGranulocytes": "CBC",
    "Lymphocytes": "CBC",
    "LymphocytesPercent": "CBC",
    "Metamyelocytes": "CBC",
    "MonocyteCount": "CBC",
    "Monocytes": "CBC",
    "Myelocytes": "CBC",
    "Neutrophils": "CBC",
    "NucleatedRedCells":"CBC",
    "OtherCells":"CBC",
    "PlateletCount":"CBC",
    "Promyelocytes": "CBC",
    "RedBloodCells":"CBC",
    "ReticulocyteCountAbsolute":"CBC",
    "ReticulocyteCountAutomated":"CBC",
    "WBCCount":"CBC",
    "WhiteBloodCells":"CBC",
    "aado2": "Blood Gases",
    "aado2_calc": "Blood Gases",
    "albumin":"LFTs",
    "alp": "LFTs",
    "alt": "LFTs",
    "amylase": "Enzymes",
    "aniongap": "BMP",
    "ast": "LFTs",
    "baseexcess": "Blood Gases",
    "bicarbonate": "Blood Gases",
    "bilirubin_direct": "LFTs",
    "bilirubin_indirect": "LFTs",
    "bilirubin_total": "LFTs",
    "bun": "BMP",
    "calcium": "BMP",
    "carboxyhemoglobin": "Blood Gases",
    "chloride": "BMP",
    "ck_cpk": "Enzymes",
    "ck_mb": "Enzymes",
    "creatinine": "BMP",
    "crp": "Inflammation",
    "d_dimer": "Inflammation",
    "diastolic_bp": "Vitals",
    "fibrinogen": "Coagulation",
    "fio2": "Blood Gases",
    "ggt": "LFTs",
    "globulin": "CBC",
    "glucose": "BMP",
    "heart_rate": "Vitals",
    "hematocrit": "CBC",
    "hemoglobin": "CBC",
    "inr": "Coagulation",
    "invasive_line": "Procedures",
    "lactate": "Inflammation",
    "ld_ldh": "Inflammation",
    "methemoglobin": "Blood Gases",
    "pao2fio2ratio": "Blood Gases",
    "pco2": "Blood Gases",
    "ph": "BMP",
    "po2": "Blood Gases",
    "potassium": "BMP",
    "pt": "Coagulation",
    "ptt": "Coagulation",
    "resp_rate": "Vitals",
    "so2": "Blood Gases",
    "sodium": "BMP",
    "spo2": "Vitals",
    "systolic_bp": "Vitals",
    "temperature": "Vitals",
    "thrombin": "Coagulation",
    "total_protein": "LFTs",
    "totalco2": "Blood Gases",
    "ventilation": "Procedures",
}
