# Hard-coding a list of features as a reference so that other modules can be sure of the feature count / order
features = [
    "basophils_abs",
    "eosinophils_abs",
    "lymphocytes_abs",
    "monocytes_abs",
    "neutrophils_abs",
    "basophils",
    "eosinophils",
    "lymphocytes",
    "monocytes",
    "neutrophils",
    "atypical_lymphocytes",
    "bands",
    "immature_granulocytes",
    "metamyelocytes",
    "nrbc",
    "hematocrit",
    "hemoglobin",
    "mch",
    "mchc",
    "mcv",
    "platelet",
    "rbc",
    "rdw",
    "wbc",
    "aado2",
    "aado2_calc",
    "albumin",
    "alp",
    "alt",
    "amylase",
    "aniongap",
    "ast",
    "baseexcess",
    "bicarbonate",
    "bilirubin_direct",
    "bilirubin_indirect",
    "bilirubin_total",
    "bun",
    "calcium",
    "carboxyhemoglobin",
    "chloride",
    "ck_cpk",
    "ck_mb",
    "creatinine",
    "crp",
    "d_dimer",
    "diastolic_bp",
    "fibrinogen",
    "fio2",
    "ggt",
    "globulin",
    "glucose",
    "heart_rate",
    "hematocrit",
    "hemoglobin",
    "inr",
    "invasive_line",
    "lactate",
    "ld_ldh",
    "methemoglobin",
    "pao2fio2ratio",
    "pco2",
    "ph",
    "po2",
    "potassium",
    "pt",
    "ptt",
    "resp_rate",
    "so2",
    "sodium",
    "spo2",
    "systolic_bp",
    "temperature",
    "thrombin",
    "total_protein",
    "totalco2",
    "ventilation",
    "age",
    "gender",
]

feat_category_map = {
    "basophils_abs": "cbc",
    "eosinophils_abs": "cbc",
    "lymphocytes_abs": "cbc",
    "monocytes_abs": "cbc",
    "neutrophils_abs": "cbc",
    "basophils": "cbc",
    "eosinophils": "cbc",
    "lymphocytes": "cbc",
    "monocytes": "cbc",
    "neutrophils": "cbc",
    "atypical_lymphocytes": "cbc",
    "bands": "cbc",
    "immature_granulocytes": "cbc",
    "metamyelocytes": "cbc",
    "nrbc": "cbc",
    "hematocrit": "cbc",
    "hemoglobin": "cbc",
    "mch": "cbc",
    "mchc": "cbc",
    "mcv": "cbc",
    "platelet": "cbc",
    "rbc": "cbc",
    "rdw": "cbc",
    "wbc": "cbc",
    "aado2": "Blood Gases",
    "aado2_calc": "Blood Gases",
    "albumin": "LFTs",
    "alp": "LFTs",
    "alt": "LFTs",
    "amylase": "Enzymes",
    "aniongap": "BMP",
    "ast": "LFTs",
    "baseexcess": "Blood Gases",
    "bicarbonate": "Blood Gases",
    "bilirubin_direct": "LFTs",
    "bilirubin_indirect": "LFTs",
    "bilirubin_total": "LFTs",
    "bun": "BMP",
    "calcium": "BMP",
    "carboxyhemoglobin": "Blood Gases",
    "chloride": "BMP",
    "ck_cpk": "Enzymes",
    "ck_mb": "Enzymes",
    "creatinine": "BMP",
    "crp": "Inflammation",
    "d_dimer": "Inflammation",
    "diastolic_bp": "Vitals",
    "fibrinogen": "Coagulation",
    "fio2": "Blood Gases",
    "ggt": "LFTs",
    "globulin": "CBC",
    "glucose": "BMP",
    "heart_rate": "Vitals",
    "hematocrit": "CBC",
    "hemoglobin": "CBC",
    "inr": "Coagulation",
    "invasive_line": "Procedures",
    "lactate": "Inflammation",
    "ld_ldh": "Inflammation",
    "methemoglobin": "Blood Gases",
    "pao2fio2ratio": "Blood Gases",
    "pco2": "Blood Gases",
    "ph": "BMP",
    "po2": "Blood Gases",
    "potassium": "BMP",
    "pt": "Coagulation",
    "ptt": "Coagulation",
    "resp_rate": "Vitals",
    "so2": "Blood Gases",
    "sodium": "BMP",
    "spo2": "Vitals",
    "systolic_bp": "Vitals",
    "temperature": "Vitals",
    "thrombin": "Coagulation",
    "total_protein": "LFTs",
    "totalco2": "Blood Gases",
    "ventilation": "Procedures",
    "age": "Age",
    "gender": "Gender",
}
